### ISSUE TITLE
Rules Engine unable to expand ~timestampu during rules evaluation

### ISSUE THREAD

**Issue by shtomar-adb** [adobe/aepsdk-rulesengine-ios#45]
### Expected Behaviour
Rules Engine should be able to expand ~timestampu during rules evaluation

### Actual Behaviour
During rules evaluation, i Observed in class ComparisonExpression's evaluate function the resolved value for ~timestampu is nil. This is leading to rules not matching.

**Comment by yangyansong-adbe** [comment]
This bug is fixed in Core  https://github.com/adobe/aepsdk-core-ios/pull/642
