### ISSUE TITLE
XCode 14.3 results in "underlying Objective-C module 'AEPFulesEngine' not found"

### ISSUE THREAD

**Issue by ApplyFrank** [adobe/aepsdk-rulesengine-ios#68]
### Expected Behaviour
Project is able to build in Xcode 14.3

### Actual Behaviour
Project doesn't build in Xcode 14.3 but builds without problems in Xcode 14.2

### Reproduce Scenario (including but not limited to)
In our project we have React Native and SwiftUI and UIKit. In our project we would run npm install and in our package.json there are scripts to pod install.
With Xcode 14.2 we were able to build the project fine. But with 14.3 it says AEP has some weird module issues. 
if I add use_frameworks! then we get a ReactNative error. When I remove AEP analytics, the project builds but just shows errors where we called it. 
<img width="349" alt="RNError" src="https://github.com/adobe/aepsdk-rulesengine-ios/assets/105822946/dc504c05-9bb4-416a-b341-0b6a6a0938b3">

The question is, is there a build setting or a config in AEP that I'm missing or is missing in the pods? 
Thank you please help 

#### Steps to Reproduce
Create a project with AEP cocoapods and build with Xcode 14.3 

#### Platform and Version
Xcode Version 14.3 (14E222b) 

#### Sample Code that illustrates the problem

require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

ENV['SWIFT_VERSION'] = '5.5'

platform :ios, '15.0'
install! 'cocoapods', :deterministic_uuids => false

inhibit_all_warnings!

target 'PROJECTNAMEHERE' do

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'SwiftFormat/CLI', '~> 0.49.14'

  pod 'lottie-ios'

  pod 'AEPUserProfile', '~> 3.0'
  pod 'AEPCore', '~> 3.0'
  pod 'AEPIdentity', '~> 3.0'
  pod 'AEPSignal', '~>3.0'
  pod 'AEPLifecycle', '~>3.0'
  pod 'AEPAnalytics', '~> 3.0'

  target 'StudioONETests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end

#### Logs taken while reproducing problem
<img width="1792" alt="AEPError" src="https://github.com/adobe/aepsdk-rulesengine-ios/assets/105822946/9a335682-2dc8-4add-8175-2e6d36f4390f">

**Comment by cdhoffmann** [comment]
Hey @ApplyFrank. Can you please fill out the issue template you left blank?

**Comment by ApplyFrank** [comment]
Hi @cdhoffmann Sorry, I accidentally clicked enter before I wrote anything, All is updated please let me know if you need additional information.

**Comment by cdhoffmann** [comment]
No problem. Thanks. So this is a known issue that we are looking into. For now though, we have a few workarounds you can try:

We are still working on the underlying issue but in the meantime you can use one of these workarounds

1) Linking as static frameworks by adding`use_frameworks! :linkage => :static` to your Podfile. Flipper does not work when `use_frameworks` is enabled, and you should remove it from Podfile. 

2) Adding the `-no-verify-emitted-module-interface` flag to failing targets to avoid verification failure.
You can add the following post install hook to your Podfile to automatically add this flag to AEP library targets. 
```
post_install do |installer|
  installer.pods_project.targets.each do |t|
    if t.name.start_with?("AEP")
      t.build_configurations.each do |bc|
          bc.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -no-verify-emitted-module-interface'
      end
    end
  end
end
```

**Comment by ApplyFrank** [comment]
Hi @cdhoffmann thanks so much for the tips ! 
I tried the steps but now I'm getting 
![Screenshot 2023-05-15 at 11 46 05 AM](https://github.com/adobe/aepsdk-rulesengine-ios/assets/105822946/7d646802-7679-40e4-8b71-346501e7f650)

previously I already tried use_frameworks! :linkage => :static
and also added -no-verify-emitted-module-interface to the project settings in my project Target, 
I deleted Pod.lock and Pods folder -> delete Derived Data -> clean project but still doesn't work. 
Please take a look at my update podfile and let me know if I did it right 

require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

ENV['SWIFT_VERSION'] = '5.5'

platform :ios, '15.0'
install! 'cocoapods', :deterministic_uuids => false

inhibit_all_warnings!

use_frameworks! :linkage => :static

target 'ProjectnameHere' do

  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'SwiftFormat/CLI', '~> 0.49.14'

  pod 'lottie-ios'

  # Adobe Analytics
  pod 'AEPUserProfile', '~> 3.0'
  pod 'AEPCore', '~> 3.0'
  pod 'AEPIdentity', '~> 3.0'
  pod 'AEPSignal', '~>3.0'
  pod 'AEPLifecycle', '~>3.0'
  pod 'AEPAnalytics', '~> 3.0'

  target 'StudioONETests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |t|
      if t.name.start_with?("AEP")
        t.build_configurations.each do |bc|
            bc.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -no-verify-emitted-module-interface'
        end
      end
    end
  end
end

**Comment by cdhoffmann** [comment]
Does the error show up in the build logs? If so can you share it. If not, can you share what line its complaining on?

**Comment by ApplyFrank** [comment]
The error doesn't show up in AEP at all actually, it shows up in my code, but it hasn't changed since 14.2. Would the Logs be in Derived Data ?

**Comment by ApplyFrank** [comment]
In the logs I found this 
`/Users/frank/Developer/Project/cc/mobile/ios/Project/UI Components/Teams/TeamsUserProfile.swift:16:25: error: failed to produce diagnostic for expression; please submit a bug report (https://swift.org/contributing/#reporting-bugs)
    var body: some View {`

**Comment by cdhoffmann** [comment]
What is on line 16 of that file?

**Comment by ApplyFrank** [comment]
it's just `var body: some View` 
but I think I narrowed it down to this `@Environment(\.cachingAsyncImageURLSession) private var urlSession` in our code
where ever theres a image cache, it produces that error
and by commenting that out I'm able to build successfully. 
Thank you so much @cdhoffmann  !

**Comment by cdhoffmann** [comment]
Awesome. No problem.
